# Configuration pour les déploiements Kubernetes

# Définition du premier déploiement
apiVersion: {{ .Values.appVersion }}  # Version de l'API Kubernetes
kind: {{ .Values.kindName }}  # Type de ressource, par exemple, "Deployment"
metadata:
  name: {{ .Values.appNameQ }}-deployment # Nom du déploiement
spec:
  selector:
    matchLabels:
      app: {{ .Values.appNameQ }}  # Étiquette utilisée pour sélectionner les pods
  replicas: {{ .Values.replicaCount }}  # Nombre de réplicas
  template: # template for the pods
    metadata:
      labels:
        app: {{ .Values.appNameQ }}  # Étiquette pour les pods
    spec:
      containers:
      - name: {{ .Values.appNameQ }}-container  # Nom du conteneur
        image: {{ .Values.dockerRepoName | default "richardchesterwood" | lower }}/k8s-fleetman-queue:release2  # Image Docker à utiliser
        resources:
          requests:
            memory: {{ .Values.resources.containerMemory }}  # Quantité de mémoire demandée
            cpu: {{ .Values.resources.containerCPU }}  # Quantité de CPU demandée

---

# Définition du deuxième déploiement
apiVersion: {{ .Values.appVersion }}
kind: {{ .Values.kindName }}
metadata:
  name: {{ .Values.appNameS }}-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Values.appNameS }}
  replicas: {{ .Values.replicaCount }}
  template: # template for the pods
    metadata:
      labels:
        app: {{ .Values.appNameS }}
    spec:
      containers:
      - name: {{ .Values.appNameS }}-container
        image: {{ .Values.dockerRepoName | default "richardchesterwood"  |  lower }}/k8s-fleetman-position-simulator:release2
        env:
        - name: {{ .Values.env.envName }}
          value: {{ .Values.env.envValue }}
        resources:
          requests:
            memory: 600Mi
            cpu: 600m

---

# Définition du troisième déploiement
apiVersion: {{ .Values.appVersion }}
kind: {{ .Values.kindName }}
metadata:
  name: {{ .Values.appNameT }}-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Values.appNameT }}
  replicas: {{ .Values.replicaCount }}
  template: # template for the pods
    metadata:
      labels:
        app: {{ .Values.appNameT }}
    spec:
      containers:
      - name: {{ .Values.appNameT }}-container
        image: {{ .Values.dockerRepoName | default "richardchesterwood"  |  lower }}/k8s-fleetman-position-tracker:release3
        env:
        - name: {{ .Values.env.envName }}
          value: {{ .Values.env.envValue }}
        resources:
          requests:
            memory: 600Mi
            cpu: 50m

---

# Définition du quatrième déploiement

apiVersion: {{ .Values.appVersion }}
kind: {{ .Values.kindName }}
metadata:
  name: {{ .Values.appNameA }}-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Values.appNameA }}
  replicas: {{ .Values.replicaCount }}
  template: # template for the pods
    metadata:
      labels:
        app: {{ .Values.appNameA }}
    spec:
      containers:
      - name: {{ .Values.appNameA }}-container
        image: {{ .Values.dockerRepoName | default "richardchesterwood"  |  lower }}/k8s-fleetman-api-gateway:release2
        env:
        - name: {{ .Values.env.envName }}
          value: {{ .Values.env.envValue }}
        resources:
          requests:
            memory: 1000Mi
            cpu: 50m

---

# Définition du cinquième déploiement
apiVersion: {{ .Values.appVersion }}
kind: {{ .Values.kindName }}
metadata:
  name: {{ .Values.appNameW }}-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Values.appNameW }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.appNameW }}
    spec:
      containers:
      - name: {{ .Values.appNameW }}-container
        image: {{ .Values.dockerRepoName | default "richardchesterwood"  |  lower }}/k8s-fleetman-webapp-angular:release2
        env:
        - name: {{ .Values.env.envName }}
          value: {{ .Values.env.envValue }}
        resources:
          requests:
            memory: 100Mi
            cpu: 50m