# Configuration pour l'autoscaler horizontal des pods

apiVersion: autoscaling/v1 # Version de l'API pour lautoscaler horizontal
kind: HorizontalPodAutoscaler # Type de ressource, ici un autoscaler horizontal
metadata:
  name: api-gateway # Nom de lautoscaler
  namespace: default # Namespace où lautoscaler est déployé
spec:
  maxReplicas: 4 # Nombre max de réplicas
  minReplicas: 1 # Nombre min de réplicas
  scaleTargetRef:
    apiVersion: apps/v1 # Version de l'API pour la référence de l'objectif de mise à l'échelle
    kind: Deployment # Type de ressource à mettre à l'échelle, ici un déploiement
    name: api-gateway # Nom du déploiement à mettre à l'échelle
  targetCPUUtilizationPercentage: 400 # Seuil de l'utilisation du CPU pour le déclenchement de la mise à l'échelle
