# Configuration pour l'Ingress
apiVersion: networking.k8s.io/v1 # Version de l'API pour Ingress
kind: Ingress # Type de ressource, ici un Ingress
metadata:
  name: routing # Nom de l'Ingress
spec: 
  rules:
    - host: domain.com # Hôte pour la règle
      http:
        path: / # Chemin pour la règle HTTP
          backend:
            service:
                name: katarzyna-webapp
                port:
                  number: 80 # Port du service backend
    - host: queque.domain.com # Hôte pour la deuxième règle
      http:
        path: / # Chemin pour la deuxième règle HTTP
           pathType: Prefix
            backend:
              service:
                name: katarzyna-webapp
                port:
                  number: 8161

