# Service pour katarzyna-webapp
apiVersion: {{ .Values.versionSvc }} # Version de l'API pour le service
kind: {{ .Values.kindNameSvc }} # Type de ressource, ici un Service
metadata:
  name: katarzyna-webapp # Nom du service

spec:
  selector:
    app: {{ .Values.appNameW }}  # Label pour sélectionner les pods

  ports: # Nom du port
    - name:  {{ .Values.portName }}
      port: 80 # Port exposé par le service
      nodePort: 30081  # NodePort pour l'accès externe (type NodePort requis)

  type: {{ .Values.portTypeN }}

---
# Service pour katarzyna-queue
apiVersion: {{ .Values.versionSvc }}
kind: {{ .Values.kindNameSvc }}
metadata:
  name: katarzyna-queue

spec:
  selector:
    app: {{ .Values.appNameQ }}

  ports:
    - name: {{ .Values.portName }}
      port: 8160
      nodePort: 30015

    - name: endpoint
      port: 61616

  type: {{ .Values.portTypeN }}

---
# Service pour fleetman-position-tracker
apiVersion: {{ .Values.versionSvc }}
kind: {{ .Values.kindNameSvc }}
metadata:
  name: katarzyna-position-tracker

spec:
  selector:
    app: {{ .Values.appNameT }}

  ports:
    - name: {{ .Values.portName }}
      port: 8080

  type: {{ .Values.portTypeC }}

---
# Service pour fleetman-api-gateway
apiVersion: {{ .Values.versionSvc }}
kind: {{ .Values.kindNameSvc }}
metadata:
  name: katarzyna-api-gateway

spec:
  selector:
    app: {{ .Values.appNameA }}

  ports:
    - name: {{ .Values.portName }}
      port: 8080
      nodePort: 30020

  type: {{ .Values.portTypeN }}