# What do want?
apiVersion: v1   #Version de l'API pour la PersistentVolumeClaim.
kind: PersistentVolumeClaim   #Type de ressource Kubernetes, qui est une PersistentVolumeClaim.
metadata:
  name: mongo-pvc
spec:
  storageClassName: mylocalstorage # Nom de la classe de stockage qui définit la manière dont les données seront stockées
  accessModes:
    - ReadWriteOnce # volume peut être monté sur un seul nœud en lecture et écriture
  resources:
    requests:
      storage: 20Gi
---
# How do we want it implemented
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
spec:
  storageClassName: mylocalstorage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/some new/directory/structure/"
    type: DirectoryOrCreate