---
# déploiement pour le service Queue
apiVersion: {{ .Values.appVersion }}
kind: {{ .Values.kindName }}
metadata:
  name: {{ .Values.appNameQ }}-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Values.appNameQ }}
  replicas : {{ .Values.replicaCount }}                           # simulation de panne pour vérifier la panne replicas: 0
  template: 
    metadata:
      labels:
        app: {{ .Values.appNameQ }}
    spec:
      containers:
      - name: {{ .Values.appNameQ }}-container
        image: {{ .Values.dockerRepoName | default "richardchesterwood" | lower }}/k8s-fleetman-queue:release2

---
# déploiement pour le service Position Simulator
apiVersion: {{ .Values.appVersion }}
kind: {{ .Values.kindName }}
metadata:
  name: {{ .Values.appNameS }}-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Values.appNameS }}
  replicas: {{ .Values.replicaCount }} 
  template: # template for the pods
    metadata:
      labels:
        app: {{ .Values.appNameS }}
    spec:
      containers:
      - name: {{ .Values.appNameS }}-container
        image: {{ .Values.dockerRepoName | default "richardchesterwood" | lower }}/k8s-fleetman-position-simulator:release2
        env:
        - name: {{ .Values.env.envName }}
          value: {{ .Values.env.envValue }}

---
# déploiement pour le service Position Tracker
apiVersion: {{ .Values.appVersion }}
kind: {{ .Values.kindName }}
metadata:
  name: {{ .Values.appNameT }}-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Values.appNameT }}
  replicas: {{ .Values.replicaCount }} 
  template: # template for the pods
    metadata:
      labels:
        app: {{ .Values.appNameT }}
    spec:
      containers:
      - name: {{ .Values.appNameT }}-container
        image: r{{ .Values.dockerRepoName | default "richardchesterwood" | lower }}/k8s-fleetman-position-tracker:release3
        env:
        - name: {{ .Values.env.envName }}
          value: {{ .Values.env.envValue }}

---
# déploiement pour le service API Gateway
apiVersion: {{ .Values.appVersion }}
kind: {{ .Values.kindName }}
metadata:
  name: {{ .Values.appNameA }}-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Values.appNameA }}
  replicas: {{ .Values.replicaCount }} 
  template: # template for the pods
    metadata:
      labels:
        app: {{ .Values.appNameA }}
    spec:
      containers:
      - name: {{ .Values.appNameA }}-container
        image: {{ .Values.dockerRepoName | default "richardchesterwood" | lower }}/k8s-fleetman-api-gateway:release2
        env:
        - name: {{ .Values.env.envName }}
          value: {{ .Values.env.envValue }}

---
# déploiement pour le service Webapp
apiVersion: {{ .Values.appVersion }}
kind: {{ .Values.kindName }}
metadata:
  name: {{ .Values.appNameW }}-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Values.appNameW }}
  replicas: {{ .Values.replicaCount }} 
  template: # template for the pods
    metadata:
      labels:
        app: {{ .Values.appNameW }}
    spec:
      containers:
      - name: {{ .Values.appNameW }}-container
        image: {{ .Values.dockerRepoName | default "richardchesterwood" | lower }}/k8s-fleetman-webapp-angular:release2
        env:
        - name: {{ .Values.env.envName }}
          value: {{ .Values.env.envValue }}