# Service pour webapp
apiVersion: {{ .Values.versionSvc }}
kind: {{ .Values.kindNameSvc }}
metadata:
  name: katarzyna-webapp

spec:
  selector:
    app: {{ .Values.appNameW }}

  ports:
    - name: {{ .Values.portName }}
      port: 80
  type: LoadBalancer

---

# Service pour queue
apiVersion: {{ .Values.versionSvc }}
kind: {{ .Values.kindNameSvc }}
metadata:
  name: katarzyna-queue

spec:
  selector:
    app: {{ .Values.appNameQ }}

  ports:
    - name: {{ .Values.portName }}
      port: 8161

    - name: endpoint
      port: 61616

  type: {{ .Values.portTypeC }}


---

# Service pour position-tracker
apiVersion: {{ .Values.versionSvc }}
kind: {{ .Values.kindNameSvc }}
metadata:
  name: katarzyna-position-tracker

spec:
  selector:
    app: {{ .Values.appNameT }}

  ports:
    - name: {{ .Values.portName }}
      port: 8080

  type: {{ .Values.portTypeC }}

---

# Service pour api-gateway
apiVersion: {{ .Values.versionSvc }}
kind: {{ .Values.kindNameSvc }}
metadata:
  name: katarzyna-api-gateway

spec:
  selector:
    app: {{ .Values.appNameA }}

  ports:
    - name: {{ .Values.portName }}
      port: 8080

  type: {{ .Values.portTypeC }}