apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"name":"aws-auth","namespace":"kube-system"},"data":{"mapRoles":"- rolearn: arn:aws:iam::905418021277:role/eks-ebs-csi-driver\n  username: system:serviceaccount:kube-system:ebs-csi-controller-sa\n  groups:\n    - system:serviceaccounts\n    - eks:ebs-csi-controller-sa\n    - system:bootstrappers\n    - system:nodes\n"}}
data:
  mapRoles: |
    - rolearn: arn:aws:iam::905418021277:role/eks-ebs-csi-driver
      username: system:serviceaccount:kube-system:ebs-csi-controller-sa
      groups:
        - system:serviceaccounts
        - eks:ebs-csi-controller-sa
        - system:bootstrappers
        - system:nodes
