name: Dev Setup

on:
  workflow_dispatch:
    inputs:
      aws_region:
        description: 'AWS Region for EKS cluster'
        required: true
        default: 'eu-west-3'

jobs:
  setup_dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update kubeconfig
        run: ./script-kube-update.sh

      - name: Verify kubectl installation
        run: kubectl version --short --client
      
      - name: Set kubectl context
        run: kubectl config use-context dev-eksdemo

      - name: Run simple kubectl command
        run: kubectl get pods --all-namespaces
