apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: webapp
  template: 
    metadata: 
      labels: 
        name: webapp
    spec:
      containers:
      - name: webapp
        #image: lnebilos/webapp-angular:0.1
        image: richardchesterwood/k8s-fleetman-webapp-angular:release2
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice