name: Collect Git Logs

on:
  push:
    branches:
      - main

jobs:
  collect_logs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Get pod logs
        run: |
          kubectl get pods --all-namespaces
          kubectl get pods --namespace=default -o=name | xargs -I{} kubectl logs {} --all-containers --namespace=default >> myapp_logs.txt

      - name: Archivei logs
        uses: actions/upload-artifact@v4
        with:
          name: kubernetes-logs
          path: myapp_logs.txt
