name: Collect Git Logs

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # 1h

jobs:
  collect_logs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 
      
      - name: Check cluster info
        run: kubectl cluster-info
      
      - name: Get nodes in cluster
        run: kubectl get nodes
      
      - name: Get services in cluster
        run: kubectl get services --all-namespaces

      - name: Get logs from specific pod
        run: kubectl logs -l app=myapp --all-containers --namespace=default > myapp_logs.txt
  
      - name: Get logs from all pods
        run: |
          kubectl get pods --all-namespaces
          kubectl logs --all-containers --all-namespaces > all_pods_logs.txt


      - name: Archive logs
        uses: actions/upload-artifact@v4
        with:
          name: kubernetes-logs
          path: myapp_logs.txt
