name: Dev Setup and Logs Collection

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # Uruchamia co godzinę
  workflow_dispatch:
    inputs:
      aws_region:
        description: 'AWS Region for EKS cluster'
        required: true
        default: 'eu-west-3'

jobs:
  setup_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make eks_terraform_setup.sh executable
        run: chmod +x ./scripts/eks_terraform_setup.sh

      - name: Install kubectl
        run: |
          echo "Install kubectl..."
          curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          kubectl version --client

      - name: Set kubectl context
        run: kubectl config use-context arn:aws:eks:eu-west-3:905418021277:cluster/dev-eksdemo

      - name: Run simple kubectl command
        run: kubectl get pods --all-namespaces

      - name: Check cluster info
        run: kubectl cluster-info

      - name: Get nodes in cluster
        run: kubectl get nodes

      - name: Get services in cluster
        run: kubectl get services --all-namespaces



