name: Dev Setup and Logs Collection

on:
  workflow_dispatch:
    inputs:
      aws_region:
        description: 'AWS Region for EKS cluster'
        required: true
        default: 'eu-west-3'

jobs:
  setup_dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update kubeconfig
        run: ./script-kube-update.sh

      - name: Verify kubectl installation
        run: kubectl version --short --cli

      - name: Set kubectl context
        run: kubectl config use-context dev-eksdemo

      - name: Run simple kubectl command
        run: kubectl get pods --all-namespacesi                                                                                                                                                                    
      - name: Check cluster info
        run: kubectl cluster-info
      
      - name: Get nodes in cluster
        run: kubectl get nodes
      
      - name: Get services in cluster
        run: kubectl get services --all-namespaces

   collect_logs:
     runs-on: ubuntu-latest
     needs: setup_dev
     steps:
       - name: Checkout code
         uses: actions/checkout@v4

       - name: Get logs from specific pod
         run: kubectl logs -l app=myapp --all-containers --namespace=default > myapp_logs.txt
  
       - name: Get logs from all pods
         run: |
           kubectl get pods --all-namespaces
           kubectl logs --all-containers --all-namespaces > all_pods_logs.txt

       - name: Archive logs
         uses: actions/upload-artifact@v4
         with:
           name: kubernetes-logs
           path: 
             - myapp_logs.txt
             - all_pods_logs.txt
