name: Dev Setup and Logs Collection

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # Uruchamia co godzinę
  workflow_dispatch:
    inputs:
      aws_region:
        description: 'AWS Region for EKS cluster'
        required: true
        default: 'eu-west-3'

jobs:
  setup_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make eks_terraform_setup.sh executable
        run: chmod +x ./scripts/eks_terraform_setup.sh

      - name: Update kubeconfig
        run: ./scripts/eks_terraform_setup.sh

  collect_logs:
    runs-on: ubuntu-latest
    needs: setup_dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
            - name: Get Kubectl Version
        run: |
          kubectl version --client > kubectl_version.txt

      - name: Check Kubernetes Cluster Info
        run: kubectl cluster-info > cluster_info.txt

      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: devops-artifact
          paths:
            - kubectl_version.txt
            - cluster_info.txt

      
