name: Dev Setup and Logs Collection

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # Uruchamia co godzinę
  workflow_dispatch:
    inputs:
      aws_region:
        description: 'AWS Region for EKS cluster'
        required: true
        default: 'eu-west-3'

jobs:
  setup_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make eks_terraform_setup.sh executable
        run: chmod +x ./scripts/eks_terraform_setup.sh

      - name: Update kubeconfig
        run: ./scripts/eks_terraform_setup.sh

  collect_logs:
    runs-on: ubuntu-latest
    needs: setup_dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      
      - name: Get system logs
        run: |
          journalctl --no-pager -o short-precise > system_logs.txt
          dmesg --ctime > kernel_logs.txt

      - name: Get Docker logs
        run: |
          docker ps -a  > docker_logs.txt

      - name: Archive logs
        uses: actions/upload-artifact@v4
        with:
          name: system-logs
          paths:
            - system_logs.txt
            - kernel_logs.txt
            - docker_logs.txt
